// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_drake_ = (function() {
  function block_drake_() {
    this.run = bind(this.run, this);
    var css, drake, feed;
    css = "#instafeed {\n	display: none;\n}\n#drake-image {\n	height:100%;\n	position: relative;\n	left: -50px;\n	top: 0px;\n}";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable\" name=\"drake\">\n	<img id=\"drake-image\" src=\"img/drake.jpg\">\n	<div id=\"instafeed\"></div>\n</div>").appendTo(".drag-zone");
    drake = 14455831;
    feed = new Instafeed({
      get: 'user',
      userId: drake,
      accessToken: '2072221807.1677ed0.cfc898e6c7124300bb90d836f3e14e9d',
      clientId: 'f41df43206564056b252ae8a5cb4019e',
      error: function() {
        return console.log("instagram error");
      },
      success: (function(_this) {
        return function(json) {
          return _this.images = json.data;
        };
      })(this)
    });
    feed.run();
  }

  block_drake_.prototype.run = function() {
    var audio;
    audio = new Audio("sound/headlines.mp3");
    audio.play();
    return this.images;
  };

  return block_drake_;

})();
