// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_taylorswift_ = (function() {
  function block_taylorswift_() {
    this.run = bind(this.run, this);
    var css, feed, taylorswift;
    css = "#instafeed {\n	display: none;\n}\n#taylor-image {\n	height:130%;\n	position: relative;\n	left: -65px;\n	top:0px;\n}";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable\" name=\"taylorswift\">\n	<img id=\"taylor-image\" src=\"img/taylorswift.jpg\">\n	<div id=\"instafeed\"></div>\n</div>").appendTo(".drag-zone");
    taylorswift = 11830955;
    feed = new Instafeed({
      get: 'user',
      userId: taylorswift,
      accessToken: '2072221807.1677ed0.cfc898e6c7124300bb90d836f3e14e9d',
      clientId: 'f41df43206564056b252ae8a5cb4019e',
      error: function() {
        return console.log("instagram error");
      },
      success: (function(_this) {
        return function(json) {
          return _this.images = json.data;
        };
      })(this)
    });
    feed.run();
  }

  block_taylorswift_.prototype.run = function() {
    var audio;
    audio = new Audio("sound/blankspace.mp3");
    audio.play();
    return this.images;
  };

  return block_taylorswift_;

})();
