// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_rihanna_ = (function() {
  function block_rihanna_() {
    this.run = bind(this.run, this);
    var css, feed, rihanna;
    css = "#instafeed {\n	display: none;\n}\n#rihanna-image {\n	width:130%;\n	position: relative;\n	left: -10px;\n	bottom:0;\n}";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable\" name=\"rihanna\">\n	<img id=\"rihanna-image\" src=\"img/rihanna.jpg\">\n	<div id=\"instafeed\"></div>\n</div>").appendTo(".drag-zone");
    rihanna = 25945306;
    feed = new Instafeed({
      get: 'user',
      userId: rihanna,
      accessToken: '2072221807.1677ed0.cfc898e6c7124300bb90d836f3e14e9d',
      clientId: 'f41df43206564056b252ae8a5cb4019e',
      error: function() {
        return console.log("instagram error");
      },
      success: (function(_this) {
        return function(json) {
          return _this.images = json.data;
        };
      })(this)
    });
    feed.run();
  }

  block_rihanna_.prototype.run = function() {
    var audio;
    audio = new Audio("sound/fourfiveseconds.mp3");
    audio.play();
    return this.images;
  };

  return block_rihanna_;

})();
