// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_instagram_ = (function() {
  function block_instagram_() {
    this.run = bind(this.run, this);
    var css, feed;
    css = "		";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div id='drag20' class='draggable block4'>INSTAGRAM</div>").appendTo(".block_bank_wrapper");
    feed = new Instafeed({
      get: 'tagged',
      tagName: 'batman',
      clientId: '2ce74f3a33a6412f8d176c3603a92c0f',
      template: '<div class="instagram-captions">{{caption}}</div>'
    });
    feed.run();
  }

  block_instagram_.prototype.run = function() {
    var captions;
    captions = [];
    $(".instagram-captions").each(function() {
      return captions.push($(this).text());
    });
    console.log(captions);
    return captions;
  };

  return block_instagram_;

})();
