// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_ding_ = (function() {
  function block_ding_() {
    this.run = bind(this.run, this);
    var css;
    css = "		";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div id='drag4' class='draggable block3 block5'>DING</div>").appendTo(".block_bank_wrapper");
  }

  block_ding_.prototype.run = function() {
    var audio;
    audio = new Audio("sound/Ding.mp3");
    return audio.play();
  };

  return block_ding_;

})();
