// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_siren_ = (function() {
  function block_siren_() {
    this.run = bind(this.run, this);
    var css;
    css = "		";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div id='drag6' class='draggable block3 block5'>SIREN</div>").appendTo(".block_bank_wrapper");
  }

  block_siren_.prototype.run = function() {
    var audio;
    audio = new Audio("sound/Siren.mp3");
    return audio.play();
  };

  return block_siren_;

})();
