// Generated by CoffeeScript 1.9.3

/*
The BlockAnimation class constucts a block that can
perform neat slider animations. The following properties must be
passed in:
@id: this is the id of the div that will be filled
IT'S SO IMPORTANT THAT THIS IS NOT REPEATED

Just put something like this in the index!
<div id="test">
	<div id="siren">
		<img src="src">
	</div>
	<div id="bell">
		<img src="src">
	</div>
	<div id="samjack">
		<img src="src">
	</div>
</div>

and type something like this in js:
block = new BlockAnimation("test");

The id's in the divs that hold the content are for identifying them as active slides.
For example, if the active slide on the block is the div with id="siren", then
get_active_slide will return "siren"
 */
var BlockAnimation;

BlockAnimation = (function() {
  var add_interactors, create_HTML, make_horizontal_swiper, make_reg_swiper, make_vertical_swiper;

  function BlockAnimation(id) {
    var swiper_hor, swiper_reg, swiper_ver;
    this.id = id;
    create_HTML();
    swiper_reg = make_reg_swiper();
    swiper_hor = make_horizontal_swiper();
    swiper_ver = make_vertical_swiper();
    add_interactors();
  }


  /* Public Methods */

  BlockAnimation.prototype.get_active_slide = function() {
    var active_slide;
    active_slide = $(this.id + "-active");
    return active_slide.attr('id');
  };

  create_HTML = function() {
    var $main, slide_content;
    $main = $("#" + this.id);
    slide_content = $main.html();
    $main.html("<div class=\"swiper-container swiper-container-ver " + this.id + "-ver\">\n	<div class=\"swiper-wrapper\">\n		<div class=\"swiper-slide stop-swiping\">\n			<div id=\"vertical-frame\"></div>\n		</div>\n	</div>\n</div>\n\n<!-- this is for the border that glides horizontally -->\n<div class=\"swiper-container swiper-container-hor " + this.id + "-hor\">\n	<div class=\"swiper-wrapper\">\n		<div class=\"swiper-slide stop-swiping\">\n			<div id=\"horizontal-frame\"></div>\n		</div>\n	</div>\n</div>\n\n<!-- this is for the actual pictures -->\n<div id=\"swiper-container-reg\" class=\"swiper-container swiper-container-reg " + this.id + "-reg\">\n	<div id=\"" + this.id + "-content\" class=\"swiper-wrapper\">\n		" + slide_content + "\n	</div>\n	<!-- Add Arrows -->\n	<div class=\"swiper-button-next " + this.id + "-next\"><i class=\"fa fa-chevron-right fa-3x\"></i></div>\n	<div class=\"swiper-button-prev " + this.id + "-prev\"><i class=\"fa fa-chevron-left fa-3x\"></i></div>\n</div>");
    return $("#" + this.id + "-content").children().each(function() {
      return $(this).addClass("swiper-slide stop-swiping");
    });
  };

  add_interactors = function() {
    interact("." + this.id + "-next").on('tap', function() {
      swiper_reg.slideNext();
      swiper_ver.slideNext();
      return swiper_hor.slideNext();
    });
    return interact("." + this.id + "-prev").on('tap', function() {
      swiper_reg.slidePrev();
      swiper_ver.slidePrev();
      return swiper_hor.slidePrev();
    });
  };

  make_reg_swiper = function() {
    var swiper_reg;
    return swiper_reg = new Swiper("." + this.id + "-reg", swiper_reg = new Swiper("." + this.id + "-reg"), {
      nextButton: "." + this.id + "-next",
      prevButton: "." + this.id + "-prev",
      effect: 'coverflow',
      slideNextClass: this.id + "-active",
      noSwiping: true,
      noSwipingClass: "stop-swiping",
      slidesPerView: 3,
      spaceBetween: 30,
      speed: 800,
      loop: true,
      coverflow: {
        rotate: 50,
        stretch: 0,
        depth: 100,
        modifier: 1,
        slideShadows: false
      }
    });
  };

  make_vertical_swiper = function() {
    var swiper_ver;
    return swiper_ver = new Swiper("." + this.id + "-ver", {
      noSwiping: true,
      noSwipingClass: 'stop-swiping',
      effect: 'coverflow',
      slidesPerView: 1,
      spaceBetween: 30,
      loop: true,
      direction: 'vertical',
      speed: 800,
      coverflow: {
        rotate: 50,
        stretch: 0,
        depth: 100,
        modifier: 1,
        slideShadows: false
      }
    });
  };

  make_horizontal_swiper = function() {
    var swiper_hor;
    return swiper_hor = new Swiper("." + this.id + "-hor", {
      effect: 'coverflow',
      noSwiping: true,
      noSwipingClass: 'stop-swiping',
      slidesPerView: 1,
      spaceBetween: 30,
      speed: 800,
      loop: true,
      coverflow: {
        rotate: 50,
        stretch: 0,
        depth: 100,
        modifier: 1,
        slideShadows: false
      }
    });
  };

  return BlockAnimation;

})();
