// Generated by CoffeeScript 1.9.3

/*
README:

The BlockAnimation class constucts a block that can
perform neat slider animations. The following properties must be
passed in:
@id: this is the id of the div that will be filled
IT'S SO IMPORTANT THAT THIS IS NOT REPEATED

Just put something like this in the index!
<div id="test">
	<div id="siren">
		<img src="src">
	</div>
	<div id="bell">
		<img src="src">
	</div>
	<div id="samjack">
		<img src="src">
	</div>
</div>

and type something like this in js:
block = new block_animation_("test");

The id's in the divs that hold the content are for identifying them as active slides.
For example, if the active slide on the block is the div with id="siren", then
get_active_slide will return "siren"
 */
var block_animation_;

block_animation_ = (function() {
  function block_animation_(id) {
    this.id = id;
    this.create_HTML();
    this.swiper_reg = this.make_reg_swiper();
    this.swiper_hor = this.make_horizontal_swiper();
    this.swiper_ver = this.make_vertical_swiper();
    this.add_interactors(this.swiper_reg, this.swiper_hor, this.swiper_ver);
  }


  /* Public Methods */

  block_animation_.prototype.get_active_slide = function() {
    var $active_slide;
    $active_slide = $("." + this.id + "-active");
    console.log($active_slide[0]);
    return $active_slide.attr('id');
  };

  block_animation_.prototype.create_HTML = function() {
    var $main, slide_content;
    $main = $("#" + this.id);
    slide_content = $main.html();
    $main.html("\n<div class=\"swiper-container swiper-container-ver " + this.id + "-ver\">\n	<div class=\"swiper-wrapper\">\n		<div class=\"swiper-slide stop-swiping swiper-slide-not-reg\">\n			<div id=\"vertical-frame\"></div>\n		</div>\n	</div>\n</div>\n\n<!-- this is for the border that glides horizontally -->\n<div class=\"swiper-container swiper-container-hor " + this.id + "-hor\">\n	<div class=\"swiper-wrapper\">\n		<div class=\"swiper-slide stop-swiping swiper-slide-not-reg\">\n			<div id=\"horizontal-frame\"></div>\n		</div>\n	</div>\n</div>\n\n<!-- this is for the actual pictures -->\n<div id=\"swiper-container-reg\" class=\"swiper-container swiper-container-reg " + this.id + "-reg\">\n	<div id=\"" + this.id + "-content\" class=\"swiper-wrapper general-content\">\n		" + slide_content + "\n	</div>\n	<!-- Add Arrows -->\n	<div class=\"swiper-button-next " + this.id + "-next\"><!--<i class=\"fa fa-chevron-right fa-3x\"></i>--></div>\n	<div class=\"swiper-button-prev " + this.id + "-prev\"><!--<i class=\"fa fa-chevron-left fa-3x\"></i>--></div>\n</div>\n");
    return $("#" + this.id + "-content").children().each(function() {
      return $(this).addClass("swiper-slide stop-swiping set-picture-size");
    });
  };

  block_animation_.prototype.add_interactors = function() {
    var swiper_hor, swiper_reg, swiper_ver;
    swiper_reg = this.swiper_reg;
    swiper_ver = this.swiper_ver;
    swiper_hor = this.swiper_hor;
    interact("." + this.id + "-next").on('tap', (function(_this) {
      return function() {
        _this.swiper_reg.slideNext();
        _this.swiper_ver.slideNext();
        return _this.swiper_hor.slidePrev();
      };
    })(this));
    return interact("." + this.id + "-prev").on('tap', (function(_this) {
      return function() {
        _this.swiper_reg.slidePrev();
        _this.swiper_ver.slidePrev();
        return _this.swiper_hor.slideNext();
      };
    })(this));
  };

  block_animation_.prototype.make_reg_swiper = function() {
    return new Swiper("." + this.id + "-reg", {
      nextButton: "." + this.id + "-next",
      prevButton: "." + this.id + "-prev",
      effect: 'coverflow',
      slideNextClass: this.id + "-active",
      noSwiping: true,
      noSwipingClass: "stop-swiping",
      slidesPerView: 3,
      spaceBetween: 1,
      speed: 800,
      loop: true,
      coverflow: {
        rotate: 50,
        stretch: 100,
        depth: 100,
        modifier: 1,
        slideShadows: false
      }
    });
  };

  block_animation_.prototype.make_vertical_swiper = function() {
    return new Swiper("." + this.id + "-ver", {
      noSwiping: true,
      noSwipingClass: 'stop-swiping',
      effect: 'coverflow',
      slidesPerView: 1,
      spaceBetween: 20,
      loop: true,
      direction: 'vertical',
      speed: 800,
      coverflow: {
        rotate: 50,
        stretch: 0,
        depth: 100,
        modifier: 1,
        slideShadows: false
      }
    });
  };

  block_animation_.prototype.make_horizontal_swiper = function() {
    return new Swiper("." + this.id + "-hor", {
      effect: 'coverflow',
      noSwiping: true,
      noSwipingClass: 'stop-swiping',
      slidesPerView: 1,
      spaceBetween: 30,
      speed: 800,
      loop: true,
      coverflow: {
        rotate: 50,
        stretch: 0,
        depth: 100,
        modifier: 1,
        slideShadows: false
      }
    });
  };

  return block_animation_;

})();
