// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_place_holder_ = (function() {
  function block_place_holder_() {
    this.run = bind(this.run, this);
    var css;
    css = "		";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable\" name=\"extra\">\n	TBD\n</div>").appendTo(".drag-zone");
  }

  block_place_holder_.prototype.run = function() {
    alert("Place holder block, no run function!");
    return console.log("Place holder block, no run function");
  };

  return block_place_holder_;

})();
