// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_array_test_ = (function() {
  function block_array_test_() {
    this.run = bind(this.run, this);
    var css;
    css = "		";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div id='drag16' class='draggable block4'>ARRAY_TEST</div>").appendTo(".block_bank_wrapper");
  }

  block_array_test_.prototype.run = function() {
    return [31, 32, 33, 34, 36, 69, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1];
  };

  return block_array_test_;

})();
