// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_color_ = (function() {
  function block_color_() {
    this.run = bind(this.run, this);
    var css;
    css = "		";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable\" name=\"color\">\n	<input id=\"text_input\" type=\"color\" value=\"simple color\" name=\"image\"/>\n</div>").appendTo(".drag-zone");
  }

  block_color_.prototype.run = function() {
    return $("body").css({
      backgroundColor: $("#text_input").val()
    });
  };

  return block_color_;

})();
