// Generated by CoffeeScript 1.9.3
var Block;

Block = (function() {
  Block.location = "location";

  Block.point = "point";

  Block.MY_LOCATION = 0;

  Block.MY_AREA = 1;

  function Block(blockID) {
    this.blockID = blockID;
    switch (this.blockID) {
      case this.MY_LOCATION:
        createMyLocation();
        break;
      case this.MY_AREA:
        createMyArea();
        break;
      default:
        console.log("BAD!");
    }
  }

  return Block;

})();
