// Generated by CoffeeScript 1.6.2
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_ding_ = (function() {
  function block_ding_() {
    this.run = __bind(this.run, this);
    var css;

    css = "";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("\n<div class=\"drag-wrap draggable\" name=\"ding\">\n	DING\n</div>").appendTo(".drag-zone");
  }

  block_ding_.prototype.run = function() {
    var audio;

    audio = new Audio("sound/Ding.mp3");
    return audio.play();
  };

  return block_ding_;

})();
