// Generated by CoffeeScript 1.6.2
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_text_to_speech_ = (function() {
  function block_text_to_speech_() {
    this.run = __bind(this.run, this);
    var css,
      _this = this;

    css = "#text_field{\n	font-size: 30px;\n	text-align: center;\n	position: absolute;\n	top: -40px;\n	left: 40px;\n}\n\n#text_to_speech_input {\n	position: absolute;\n	top: 150px;\n	left: 40px;\n	width: 200px;\n	font-size: 25px;\n}";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"\">\n	<div id=\"text_field\">SPEAK TO ME</div>\n	<input id=\"text_to_speech_input\" type=\"text\" name=\"image\" value=\"Enter Text\"><br>\n</div>").appendTo(".block_bank_wrapper");
    this.$input = $("#text_to_speech_input");
    interact("#drag16").on('tap', function(event) {
      return _this.$input.focus();
    });
  }

  block_text_to_speech_.prototype.run = function() {
    var text;

    console.log(this.$input.val());
    text = this.$input.val();
    return responsiveVoice.speak(text);
  };

  return block_text_to_speech_;

})();
