// Generated by CoffeeScript 1.6.2
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_display_image_ = (function() {
  function block_display_image_() {
    this.run = __bind(this.run, this);
    var css;

    css = "";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable\" name=\"display_image\">\n	DISPLAY IMAGE\n</div>").appendTo(".drag-zone");
  }

  block_display_image_.prototype.run = function(obj) {
    var object_has_key;

    object_has_key = function(obj, prop) {
      var p;

      for (p in obj) {
        if (obj.hasOwnProperty(p)) {
          if (p === prop) {
            return obj[p];
          } else if (obj[p] instanceof Object) {
            return object_has_key(obj[p], prop);
            console.log(2);
          }
        }
      }
      return null;
    };
    obj = object_has_key(obj, 'text');
    if (obj) {
      return console.log(obj);
    } else {
      return console.log('false');
    }
  };

  return block_display_image_;

})();
