// Generated by CoffeeScript 1.6.2
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_text_to_speech_ = (function() {
  function block_text_to_speech_() {
    this.run = __bind(this.run, this);
    var css,
      _this = this;

    css = "#text_to_speech_input {\n	top: 30px;\n	left: 10px;\n	width: 80px;\n	font-size: 12px;\n}";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable\" name=\"text_to_speech\">\n	SPEAK TO ME\n	<input id=\"text_to_speech_input\" type=\"text\" name=\"image\" value=\"Enter Text\"><br>\n</div>").appendTo(".drag-zone");
    this.$input = $("#text_to_speech_input");
    interact("[name=text_to_speech]").on('tap', function(event) {
      return _this.$input.focus();
    });
  }

  block_text_to_speech_.prototype.run = function() {
    var text;

    text = this.$input.val();
    return responsiveVoice.speak(text);
  };

  return block_text_to_speech_;

})();
