// Generated by CoffeeScript 1.9.3

/*
Creating a new block 
This class has five fields:
	blockID
	type
	subtype
	info
	name
 */
var Block;

Block = (function() {

  /*
  	Types
   */
  Block.location = "location";


  /*
  	Subtypes
   */

  Block.point = "point";


  /*
  	blockIDs
   */

  Block.MY_LOCATION = 0;

  Block.MY_AREA = 1;

  function Block(blockID, info) {
    this.blockID = blockID;
    this.info = info;
    switch (this.blockID) {
      case this.MY_LOCATION:
        createMyLocation();
        break;
      case this.MY_AREA:
        createMyArea();
        break;
      default:
        console.log("BAD!");
    }
  }


  /*
  	Methods that don;t need to be accessed 
  	by the client
   */

  Block.prototype.createMyLocation = function() {};

  return Block;

})();
