// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_my_location_ = (function() {
  function block_my_location_() {
    this.run = bind(this.run, this);
    var css;
    css = "		";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div id='drag1' class='draggable block1'>MY LOCATION</div>").appendTo(".block_bank_wrapper");
  }

  block_my_location_.prototype.run = function() {};

  return block_my_location_;

})();
