// Generated by CoffeeScript 1.6.2
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_orientation_ = (function() {
  function block_orientation_() {
    this.run = __bind(this.run, this);
    var css;

    css = "";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable\" name=\"orientation\">\n    ORIENTATION\n</div>").appendTo(".drag-zone");
  }

  block_orientation_.prototype.run = function() {};

  return block_orientation_;

})();
