// Generated by CoffeeScript 1.6.2
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.operator_equals_ = (function() {
  function operator_equals_() {
    this.run = __bind(this.run, this);    $("<div id='drag3' class='draggable operator'>==</div>").appendTo(".block_bank_wrapper");
  }

  operator_equals_.prototype.run = function() {};

  return operator_equals_;

})();
