// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_siren_ = (function() {
  function block_siren_() {
    this.run = bind(this.run, this);
    var css;
    css = "#siren-image {\n	position: relative;\n	width: 40%;\n	top: 20%;\n}";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable\" name=\"siren\">\n	<img id=\"siren-image\" src=\"img/siren.png\">\n</div>").appendTo(".drag-zone");
  }

  block_siren_.prototype.run = function(cb, element) {
    var audio;
    audio = new Audio("sound/Siren.mp3");
    $(audio).bind('ended', function() {
      console.log("FINSIHED AUDIO");
      return cb();
    });
    return audio.play();
  };

  return block_siren_;

})();
