// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_text_to_speech_ = (function() {
  function block_text_to_speech_() {
    this.run = bind(this.run, this);
    var css;
    css = "#text_to_speech_input {\n	position: absolute;\n	top: 60%;\n	width: 90%;\n	left: 5%;\n}";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable\" name=\"text_to_speech\">\n	SPEAK TO ME\n	<input id=\"text_to_speech_input\" value=\"ENTER TEXT\">\n</div>").appendTo(".drag-zone");
    this.$input = $("#text_to_speech_input");
    interact("[name=text_to_speech]").on('tap', (function(_this) {
      return function(event) {
        _this.$input.val("");
        return _this.$input.focus();
      };
    })(this));
  }

  block_text_to_speech_.prototype.run = function(cb) {
    var text;
    text = this.$input.val();
    responsiveVoice.speak(text);
    return cb();
  };

  return block_text_to_speech_;

})();
