// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_background_image_ = (function() {
  function block_background_image_() {
    this.run = bind(this.run, this);
    var css;
    css = "		";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable\" name=\"background_image\">\n	<input id=\"background_image_input\" type=\"text\"\"/>\n</div>").appendTo(".drag-zone");
    interact("[name=background_image]").on('tap', function(event) {
      return $("#background_image_input").focus();
    });
  }

  block_background_image_.prototype.run = function(cb) {
    var url;
    url = $("#background_image_input").val();
    $("body").css({
      backgroundImage: "url(" + url + ")",
      backgroundSize: 'cover',
      backgroundPosition: 'center',
      backgroundColor: 'white'
    });
    return cb();
  };

  return block_background_image_;

})();
