// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_donut_ = (function() {
  function block_donut_() {
    this.run = bind(this.run, this);
    var css;
    css = "#drag_donut {\n	background-image: url(img/dunkin-donuts.jpg);\n	background-size: cover;\n\n}";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div id=\"drag_donut\" class=\"drag-wrap draggable\" name=\"donut\">\n</div>").appendTo(".drag-zone");
  }

  block_donut_.prototype.run = function(cb, element) {
    window.open("http://shop.dunkindonuts.com/coffee-k-cup_1997-4294959632_p01_01/#url=%2Fall_4294959632_p01_01%2F48%2Fbestselling%2F");
    return cb();
  };

  return block_donut_;

})();
