// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_block_color_ = (function() {
  function block_block_color_() {
    this.run = bind(this.run, this);
    var css;
    css = "		";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable\" name=\"block_color\" style=\"background-image:url(./img/color_bubbles.jpg)\">\n	<input type=\"image\" src=\"./img/left-arrow.png\" name=\"saveForm\" class=\"btTxt submit\" id=\"button-left-color\" style=\"width:20%;margin-bottom:45px\"/>\n	<img id=\"crayon2\" src=\"./img/crayon_red.png\" style=\"height:100%\"/>\n	<input type=\"image\" src=\"./img/right-arrow.png\" name=\"saveForm\" class=\"btTxt submit\" id=\"button-right-color\" style=\"width:20%;margin-bottom:45px\"/>\n</div>").appendTo(".drag-zone");
    interact("#button-left-color").on('tap', function() {
      var src;
      src = $("#crayon2").attr('src');
      switch (false) {
        case src !== "./img/crayon_red.png":
          return $("#crayon2").attr('src', "./img/crayon_orange.png");
        case src !== "./img/crayon_orange.png":
          return $("#crayon2").attr('src', "./img/crayon_yellow.png");
        case src !== "./img/crayon_yellow.png":
          return $("#crayon2").attr('src', "./img/crayon_green.png");
        case src !== "./img/crayon_green.png":
          return $("#crayon2").attr('src', "./img/crayon_blue.png");
        case src !== "./img/crayon_blue.png":
          return $("#crayon2").attr('src', "./img/crayon_purple.png");
        case src !== "./img/crayon_purple.png":
          return $("#crayon2").attr('src', "./img/crayon_pink.png");
        case src !== "./img/crayon_pink.png":
          return $("#crayon2").attr('src', "./img/crayon_grey.png");
        case src !== "./img/crayon_grey.png":
          return $("#crayon2").attr('src', "./img/crayon_red.png");
      }
    });
    interact("#button-right-color").on('tap', function() {
      var src;
      src = $("#crayon2").attr('src');
      switch (false) {
        case src !== "./img/crayon_grey.png":
          return $("#crayon2").attr('src', "./img/crayon_pink.png");
        case src !== "./img/crayon_pink.png":
          return $("#crayon2").attr('src', "./img/crayon_purple.png");
        case src !== "./img/crayon_purple.png":
          return $("#crayon2").attr('src', "./img/crayon_blue.png");
        case src !== "./img/crayon_blue.png":
          return $("#crayon2").attr('src', "./img/crayon_green.png");
        case src !== "./img/crayon_green.png":
          return $("#crayon2").attr('src', "./img/crayon_yellow.png");
        case src !== "./img/crayon_yellow.png":
          return $("#crayon2").attr('src', "./img/crayon_orange.png");
        case src !== "./img/crayon_orange.png":
          return $("#crayon2").attr('src', "./img/crayon_red.png");
        case src !== "./img/crayon_red.png":
          return $("#crayon2").attr('src', "./img/crayon_grey.png");
      }
    });
  }

  block_block_color_.prototype.run = function(cb) {
    var src;
    src = $("#crayon2").attr('src');
    switch (false) {
      case src !== "./img/crayon_grey.png":
        $(".drag-wrap").css({
          backgroundColor: "#cccccc"
        });
        break;
      case src !== "./img/crayon_pink.png":
        $(".drag-wrap").css({
          backgroundColor: "#FF99CC"
        });
        break;
      case src !== "./img/crayon_purple.png":
        $(".drag-wrap").css({
          backgroundColor: "#FF00FF"
        });
        break;
      case src !== "./img/crayon_blue.png":
        $(".drag-wrap").css({
          backgroundColor: "#33CCFF"
        });
        break;
      case src !== "./img/crayon_green.png":
        $(".drag-wrap").css({
          backgroundColor: "#66FF66"
        });
        break;
      case src !== "./img/crayon_yellow.png":
        $(".drag-wrap").css({
          backgroundColor: "#FFFF00"
        });
        break;
      case src !== "./img/crayon_orange.png":
        $(".drag-wrap").css({
          backgroundColor: "#FF9933"
        });
        break;
      case src !== "./img/crayon_red.png":
        $(".drag-wrap").css({
          backgroundColor: "#E62425"
        });
    }
    return cb();
  };

  return block_block_color_;

})();
