// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_vibrate_ = (function() {
  function block_vibrate_() {
    this.run = bind(this.run, this);
    var css;
    css = "		";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable\" name=\"vibrate\">\n	VIBRATE\n</div>").appendTo(".drag-zone");
  }

  block_vibrate_.prototype.run = function(cb, element) {
    return window.navigator.vibrate([200, 100, 200]);
  };

  return block_vibrate_;

})();
