// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_sound_ = (function() {
  function block_sound_() {
    this.run = bind(this.run, this);
    var css;
    css = "		";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div id=\"sound-block\" class=\"drag-wrap draggable\" name=\"sound\">\n	<div id=\"ding-icon\">\n		<img src=\"img/bell.png\">\n	</div>\n	<div id=\"siren-icon\">\n		<img src=\"img/siren.png\">\n	</div>\n	<div id=\"drum-icon\">\n		<img src=\"img/drum.png\">\n	</div>\n</div>").appendTo(".drag-zone");
    this.sound_block = new block_animation_("sound-block");
  }

  block_sound_.prototype.run = function(cb, element) {
    var active, audio;
    active = this.sound_block.get_active_slide();
    if (active === 'ding-icon') {
      audio = new Audio("sound/Ding.mp3");
      $(audio).bind('ended', function() {
        return cb();
      });
      return audio.play();
    } else if (active === 'siren-icon') {
      audio = new Audio("sound/Siren.mp3");
      $(audio).bind('ended', function() {
        return cb();
      });
      return audio.play();
    } else if (active === 'drum-icon') {
      audio = new Audio("sound/drum-fill.mp3");
      $(audio).bind('ended', function() {
        return cb();
      });
      return audio.play();
    } else {
      return console.log('error - no active icon');
    }
  };

  return block_sound_;

})();
