// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_display_text_ = (function() {
  function block_display_text_() {
    this.run = bind(this.run, this);
    var css;
    css = "		";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable\" name=\"display_text\">\n	DISPLAY TEXT\n</div>").appendTo(".drag-zone");
  }

  block_display_text_.prototype.run = function(text) {
    var background;
    background = $('<div>', {
      text: text
    }).css({
      backgroundColor: '#1c1c1c',
      position: 'absolute',
      top: 0,
      width: '100%',
      height: '100%',
      zIndex: 90,
      color: 'white',
      fontFamily: "'Amaranth', 'sans-serif'",
      padding: 100
    }).appendTo("body");
    return textFit(background[0], {
      alignVert: true,
      alignHoriz: true,
      multiLine: true,
      maxFontSize: 300
    });
  };

  return block_display_text_;

})();
