// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_tinder_ = (function() {
  function block_tinder_() {
    this.run = bind(this.run, this);
    var css;
    css = "#tinder_drag {\n  background-image: url(http://media.bestofmicro.com/K/U/423246/original/mini.png);\n  background-size: cover;\n}\n\n#viewport {\n  width: 100%;\n  height: 100%;\n  position: relative;\n  left: auto;\n  right: auto;\n}\n\n#description {\n  top: 0;\n  bottom: 0;\n  left: 0;\n  right: 0;\n  margin-top: 0;\n  margin: auto;\n  position: absolute;\n  font-size: 12px;\n  margin-top: 220px;\n  width: 220px;\n}\n\n#viewport li {\n  width: 250px;\n  height: 350px;\n  list-style: none;\n  background: #ff6666;\n  border-radius: 5px;\n  top:0;\n  bottom: 0;\n  left: 0;\n  right: 0;\n  margin: auto;\n  position: absolute;\n  text-align: center;\n  box-shadow: 0 0 2px rgba(0, 0, 0, 0.2), 1px 1px 1px rgba(0, 0, 0, 0.2);\n  text-align: center;\n  border: 15px solid #ECECEC;\n  box-sizing: border-box;\n  cursor: default;\n}\n\n#viewport li.added {\n  background: white;\n}\n\n#viewport li.in-deck:nth-child(3) {\n  top: 2px;\n  transform: translate(2px, 2px) rotate(0.4deg);\n}\n\n#viewport li.in-deck:nth-child(2) {\n  top: 4px;\n  transform: translate(-4px, -2px) rotate(-1deg);\n}\n\n#viewport li.in-deck:nth-child(4) {\n  top: 2px;\n  transform: translate(5px, 5px) rotate(1deg);\n}\n\n#viewport li.in-deck:nth-child(5) {\n  top: 4px;\n  transform: translate(-5px, -5px) rotate(-1deg);\n}";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div id = \"tinder_drag\" class=\"drag-wrap draggable\" name=\"tinder\">\n</div>").appendTo(".drag-zone");
  }

  window.tinder_yes_entries = [];

  window.tinder_no_entries = [];

  block_tinder_.prototype.run = function(cb, entry) {
    var audio, description, stack, url;
    console.log(entry);
    audio = new Audio();
    audio.src = entry.preview_url;
    audio.play();
    if (entry.album === void 0) {
      url = entry.images.standard_resolution.url;
      description = entry.caption.text;
    } else {
      url = entry.album.images[0].url;
      description = "Track: " + entry.name;
    }
    $('<div id="white-background"></div><div id="image-div"></div><div id="viewport"> <ul class="stack"> <li class="in-deck"></li> <li class="in-deck"></li> <li class="in-deck"></li> <li class="in-deck"></li> <li class="in-deck"></li> <li class="in-deck"></li> </ul> </div>').appendTo("body");
    $('#white-background').css({
      backgroundColor: 'white',
      backgroundSize: 'cover',
      backgroundPosition: 'center',
      position: 'fixed',
      margin: 0,
      top: 0,
      bottom: 0,
      right: 0,
      left: 0,
      width: '100%',
      height: '100%',
      zIndex: 90
    });
    $('#image-div').css({
      backgroundImage: "url(" + url + ")",
      backgroundSize: 'cover',
      backgroundPosition: 'center',
      position: 'fixed',
      margin: 0,
      top: '-50%',
      bottom: 0,
      right: 0,
      left: '-50%',
      width: '200%',
      height: '200%',
      zIndex: 100,
      opacity: 0.35,
      transform: 'rotate(15deg)'
    });
    $('#viewport').css({
      maxWidth: '120%',
      maxHeight: '100%',
      bottom: 0,
      left: 0,
      margin: 'auto',
      overflow: 'auto',
      position: 'fixed',
      right: 0,
      top: 0,
      zIndex: 110
    });
    $(".stack").prepend("<li id = 'active-entry' class='in-deck added'><img src=" + url + " width='100%'; height='200px'><div id='description'>" + description + "</div></li>");
    stack = gajus.Swing.Stack();
    stack.createCard(document.querySelector('.stack li.in-deck'));
    return stack.on('throwout', (function(_this) {
      return function(e) {
        audio.pause();
        if (e.throwDirection === 1) {
          window.tinder_no_entries.push(entry);
        }
        if (e.throwDirection !== 1) {
          window.tinder_yes_entries.push(entry);
        }
        e.target.remove();
        e.target.classList.remove("in-deck");
        return cb();
      };
    })(this));
  };

  return block_tinder_;

})();
