// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

this.block_weather_ = (function() {
  function block_weather_() {
    this.run = bind(this.run, this);
    var css;
    css = "		";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div id=\"weather-block\" class=\"drag-wrap draggable\" name=\"weather\">\n	<div id=\"sunny-icon\">\n		<img src=\"img/sunny.png\">\n	</div>\n	<div id=\"cloudy-icon\">\n		<img src=\"img/cloudy2.png\">\n	</div>\n	<div id=\"rainy-icon\">\n		<img src=\"img/rainy.png\">\n	</div>\n</div>").appendTo(".drag-zone");
    this.weather_block = new block_animation_("weather-block");
  }

  block_weather_.prototype.run = function(cb, element) {
    var active, cloudy_codes, condition, rain_codes, sunny_codes;
    active = this.weather_block.get_active_slide();
    condition = null;
    if (active === "rainy-icon") {
      condition = 'rainy';
    }
    if (active === "cloudy-icon") {
      condition = 'cloudy';
    }
    if (active === "sunny-icon") {
      condition = 'sunny';
    }
    rain_codes = [3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 35, 37, 38, 39, 40, 41, 42, 43, 45, 46, 47];
    cloudy_codes = [19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 44];
    sunny_codes = [31, 32, 33, 34, 36];
    return navigator.geolocation.getCurrentPosition((function(_this) {
      return function(position) {
        var myLat, myLng;
        myLat = position.coords.latitude;
        myLng = position.coords.longitude;
        return $.simpleWeather({
          async: false,
          location: myLat + "," + myLng,
          unit: 'f',
          success: function(weather) {
            var code;
            code = parseInt(weather.todayCode);
            if (((condition === "rainy") && (indexOf.call(rain_codes, code) >= 0)) || ((condition === "cloudy") && (indexOf.call(cloudy_codes, code) >= 0)) || ((condition === "sunny") && (indexOf.call(sunny_codes, code) >= 0))) {
              return cb(true);
            } else {
              return cb(false);
            }
          },
          error: function(error) {
            alert('my_weather error');
            console.log(error);
            return cb(false);
          }
        });
      };
    })(this));
  };

  return block_weather_;

})();
