// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_nlp_ = (function() {
  function block_nlp_() {
    this.run = bind(this.run, this);
    var css, switch_feeling;
    this.happy_picture_path = "img/thumbs_up.jpg";
    this.sad_picture_path = "img/thumbs_down.png";
    css = "#nlp-block {\n	background-image: url(" + this.happy_picture_path + ");\n	background-size: cover;\n}\n\n#nlp_input {\n	position: absolute;\n	top: 65%;\n	width: 80%;\n	left: 10%;\n	text-align: center;\n	font-size: 11px;\n	background: #ACF0F2;\n	z-index: 20;\n	opacity: 0.6;\n}";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div id=\"nlp-block\" class=\"drag-wrap draggable\" name=\"nlp\">\n	<img src=\"./img/left-arrow.png\" id=\"button-left-nlp\" style=\"width:20%;margin-bottom:-15px; margin-left: -5px;\"/>\n	<input id=\"nlp_input\" type=\"text\" value=\"FEELING\">\n	<img src=\"./img/right-arrow.png\" id=\"button-right-nlp\" style=\"width:20%;margin-bottom:-15px;margin-left: 60px;\"/>\n\n</div>").appendTo(".drag-zone");
    switch_feeling = (function(_this) {
      return function() {
        var background, happy_index, sad_index;
        background = $("#nlp-block").css('background-image');
        happy_index = background.indexOf(_this.happy_picture_path);
        sad_index = background.indexOf(_this.sad_picture_path);
        if (happy_index !== -1) {
          return $("#nlp-block").css('background-image', "url(" + _this.sad_picture_path + ")");
        } else if (sad_index !== -1) {
          return $("#nlp-block").css('background-image', "url(" + _this.happy_picture_path + ")");
        }
      };
    })(this);
    interact("#button-left-nlp").on('tap', function() {
      return switch_feeling();
    });
    interact("#button-right-nlp").on('tap', function() {
      return switch_feeling();
    });
    interact("#nlp_input").on('tap', function(event) {
      $("#nlp_input").val("");
      return $("#nlp_input").focus();
    });
    this.sentiment = "";
  }

  block_nlp_.prototype.run = function(cb, element) {
    var text;
    text = $("#nlp_input").val();
    return $.ajax({
      Accept: "application/json",
      url: "https://loudelement-free-natural-language-processing-service.p.mashape.com/nlp-text/?text=" + text,
      headers: {
        'X-Mashape-Key': 'KnJbxzvOw6msheLU1Lt6ol120y0Rp1rdwCwjsnKYyLhmdJERdO'
      },
      error: function(jqXHR, textStatus, errorThrown) {
        console.log(jqXHR);
        console.log(textStatus);
        console.log(errorThrown);
        return alert("error");
      },
      success: (function(_this) {
        return function(json, textStatus, z) {
          var background_image, is_happy, is_sad;
          _this.sentiment = json["sentiment-text"];
          background_image = $("#nlp-block").css('background-image');
          is_happy = background_image.indexOf(_this.happy_picture_path);
          is_sad = background_image.indexOf(_this.sad_picture_path);
          if (_this.sentiment === "positive" && is_happy !== -1) {
            return cb(true);
          } else if (_this.sentiment === "negative" && is_sad !== -1) {
            return cb(true);
          }
        };
      })(this)
    });
  };

  return block_nlp_;

})();
