// Generated by CoffeeScript 1.9.3
this.block_nlp_ = (function() {
  function block_nlp_() {
    var css;
    css = "#I_FEEL_text{\n	position: absolute;\n	font-size: 20px;\n	top: -30px;\n	left: 25px;\n}\n\n#nlp_input {\n	position: absolute;\n	top: 30px;\n	left: 10px;\n	width: 80px;\n	font-size: 10px;\n}";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div id=\"nlp-block\" class=\"drag-wrap draggable\" name=\"nlp\">\n	<div id=\"thumbs-up-icon\">\n		<img src=\"img/thumbs_up.png\">\n	</div>\n	<div id=\"neutral-icon\">\n		<img src=\"img/neutral.png\">\n	</div>\n	<div id=\"thumbs-down-icon\">\n		<img src=\"img/thumbs_down.png\">\n	</div>\n</div>").appendTo(".drag-zone");
    this.nlp_block = new block_animation_("nlp-block");
    interact("#nlp_input").on('tap', function(event) {
      return $("#nlp_input").focus();
    });
    this.sentiment = "";
    $("#nlp_input").on('input propertychange', (function(_this) {
      return function(event) {
        var text;
        text = $("#nlp_input").val();
        return $.ajax({
          Accept: "application/json",
          url: "https://loudelement-free-natural-language-processing-service.p.mashape.com/nlp-text/?text=" + text,
          headers: {
            'X-Mashape-Key': 'KnJbxzvOw6msheLU1Lt6ol120y0Rp1rdwCwjsnKYyLhmdJERdO'
          },
          error: function(jqXHR, textStatus, errorThrown) {
            console.log(jqXHR);
            console.log(textStatus);
            console.log(errorThrown);
            return alert("error");
          },
          success: function(json, textStatus, z) {
            return _this.sentiment = json["sentiment-text"];
          }
        });
      };
    })(this));
    ({
      run: (function(_this) {
        return function() {
          var active;
          active = _this.nlp_block.get_active_slide();
          if (_this.sentiment === "positive" && active === "thumbs-down-icon") {
            return true;
          } else if (_this.sentiment === "negative" && active === "thumbs-up-icon") {
            return true;
          } else if (_this.sentiment === "neutral " && active === "neutral-icon") {
            return true;
          }
        };
      })(this)
    });
  }

  return block_nlp_;

})();
