// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_weather_ = (function() {
  function block_weather_() {
    this.run = bind(this.run, this);
    var css;
    console.log("GOT IN BLOCK WEATHER");
    css = "		";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div id=\"weather-block\" class=\"drag-wrap draggable\" name=\"weather\">\n	<div id=\"sunny-icon\">\n		<img src=\"img/sunny.png\">\n	</div>\n	<div id=\"cloudy-icon\">\n		<img src=\"img/cloudy2.png\">\n	</div>\n	<div id=\"rainy-icon\">\n		<img src=\"img/rainy.png\">\n	</div>\n</div>").appendTo(".drag-zone");
    this.weather_block = new block_animation_("weather-block");
  }

  block_weather_.prototype.run = function(action) {
    var active;
    active = this.weather_block.get_active_slide();
    if (active === "rainy-icon") {
      return 'rainy';
    }
    if (active === "cloudy-icon") {
      return 'cloudy';
    }
    if (active("sunny-icon")) {
      return 'sunny';
    }
  };

  return block_weather_;

})();
