// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.control_for_loop_ = (function() {
  function control_for_loop_($target) {
    this.run = bind(this.run, this);
    var append_to_this, css;
    css = "		";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    append_to_this = null;
    if ($target != null) {
      append_to_this = $target;
    } else {
      append_to_this = '.drop-zone';
    }
    this.counter_id = window.counter;
    window.counter = this.counter_id + 1;
    $("<div class='text'>FOR EACH</div>\n<div class='droppable steps droppable-" + this.counter_id + "' role='array'>LIST</div>\n<div class='text'>DO</div>\n<div class='droppable steps droppable-" + this.counter_id + "' role='action'>THIS</div>").appendTo(append_to_this);
    interact(".droppable-" + this.counter_id).dropzone({
      accept: '.draggable',
      overlap: .1,
      ondropactivate: function(event) {
        $target = $(event.target);
        return $target.addClass('can--drop');
      },
      ondragenter: function(event) {
        var $draggableElement, dropCenter, dropRect, dropzoneElement;
        $draggableElement = $(event.relatedTarget);
        dropzoneElement = event.target;
        dropRect = interact.getElementRect(dropzoneElement);
        dropCenter = {
          x: dropRect.left + dropRect.width / 2,
          y: dropRect.top + dropRect.height / 2
        };
        event.draggable.draggable({
          snap: {
            targets: [dropCenter]
          }
        });
        dropzoneElement.classList.add('can--catch');
        return $draggableElement.addClass('drop--me');
      },
      ondragleave: function(event) {
        var $relatedTarget;
        $target = $(event.target);
        $relatedTarget = $(event.relatedTarget);
        $target.removeClass('can--catch');
        $relatedTarget.removeClass('caught--it');
        return $relatedTarget.removeClass('drop--me');
      },
      ondrop: (function(_this) {
        return function(event) {
          var $related_target, block_name;
          $target = $(event.target);
          $related_target = $(event.relatedTarget);
          block_name = _.trim($related_target.text().toLowerCase());
          if ($target.attr('role') === 'array') {
            block_name = $related_target.attr("name");
            _this.array = window["block_" + block_name];
          }
          if ($target.attr('role') === 'action') {
            block_name = $related_target.attr("name");
            if (block_name === "ifthen") {
              _this.transform_action_area($target, $related_target, false);
            } else if (block_name === "forloop") {
              _this.transform_action_area($target, $related_target, true);
            } else {
              _this.action = window["block_" + block_name];
            }
          }
          return $target.addClass('caught--it');
        };
      })(this),
      ondropdeactivate: function(event) {
        $target = $(event.target);
        return $target.removeClass('can--drop', 'can--catch');
      }
    });
  }

  control_for_loop_.prototype.transform_action_area = function($target, $block, isLoop) {
    var control_condition;
    $block.remove();
    $target.html(" ");
    $target.removeClass();
    $target.css({
      "width": "auto",
      "height": "auto"
    });
    $target.attr({
      "role": "whatever"
    });
    control_condition = null;
    if (isLoop) {
      console.log("Is a for loop");
      control_condition = new control_for_loop_($target);
      new draggable_control_for_loop_();
    } else {
      console.log("Is an if consition");
      control_condition = new control_if_then_($target);
      new draggable_control_if_then_();
    }
    return this.action = control_condition;
  };

  control_for_loop_.prototype.run = function(outer_cb) {
    console.log(this.array);
    console.log("GOT IN FOR LOOP RUN");
    console.log(this.action);
    return async.forEachOfSeries(this.array.run(), (function(_this) {
      return function(element, i, cb) {
        console.log("Element: " + element);
        console.log("Value: " + i);
        _this.action.run(cb, element);
      };
    })(this), function(err) {
      if (outer_cb != null) {
        return outer_cb();
      }
    });
  };

  return control_for_loop_;

})();
