// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.control_for_loop_ = (function() {
  function control_for_loop_($target) {
    this.run = bind(this.run, this);
    var append_to_this, css, items, onScroll;
    css = "#array-zone {\n	left: 75px;\n}\n#do-text {\n	left: 115px;\n}\n#action-zone {\n	left: 255px;\n}";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    append_to_this = null;
    if ($target != null) {
      append_to_this = $target;
    } else {
      append_to_this = '.drop-zone';
    }
    this.counter_id = window.counter;
    window.counter = this.counter_id + 1;
    $("<div id='for-each-text' class='text'>FOR EACH</div>\n<div id='array-zone' class='droppable steps droppable-" + this.counter_id + "' role='array'>LIST</div>\n<div id='do-text' class='text'>DO</div>\n<div id='action-zone' class='droppable steps droppable-" + this.counter_id + "' role='action'>THIS</div>").appendTo(append_to_this);
    items = $(".drag-wrap");
    onScroll = (function(_this) {
      return function() {
        var i, pos, s2;
        i = 0;
        while (i < items.length) {
          pos = items[i].getBoundingClientRect();
          s2 = (pos.left + pos.width / 2 - (window.innerWidth / 2)) / (window.innerWidth / 1.2);
          s2 = 1 - Math.abs(s2);
          $(items[i]).css({
            '-webkit-transform': "scale(" + s2 + ")"
          });
          ++i;
        }
      };
    })(this);
    this.spot_filled = [false, false];
    interact(".droppable-" + this.counter_id).dropzone({
      accept: '.draggable',
      overlap: .1,
      ondropactivate: function(event) {
        $target = $(event.target);
        return $target.addClass('can--drop');
      },
      ondragenter: function(event) {
        var $draggableElement, dropCenter, dropRect, dropzoneElement;
        $draggableElement = $(event.relatedTarget);
        dropzoneElement = event.target;
        dropRect = interact.getElementRect(dropzoneElement);
        dropCenter = {
          x: dropRect.left + dropRect.width / 2,
          y: dropRect.top + dropRect.height / 2
        };
        event.draggable.draggable({
          snap: {
            targets: [dropCenter]
          }
        });
        dropzoneElement.classList.add('can--catch');
        return $draggableElement.addClass('drop--me');
      },
      ondragleave: function(event) {
        var $relatedTarget;
        $target = $(event.target);
        $relatedTarget = $(event.relatedTarget);
        $target.removeClass('can--catch');
        $relatedTarget.removeClass('caught--it');
        return $relatedTarget.removeClass('drop--me');
      },
      ondrop: (function(_this) {
        return function(event) {
          var $clone, $related_target, block_name, x, y;
          $target = $(event.target);
          $related_target = $(event.relatedTarget);
          block_name = _.trim($related_target.text().toLowerCase());
          if ($target.attr('role') === 'array') {
            block_name = $related_target.attr("name");
            _this.array = window["block_" + block_name];
          }
          if ($target.attr('role') === 'action') {
            block_name = $related_target.attr("name");
            if (block_name === "ifthen") {
              _this.transform_action_area($target, $related_target, false);
            } else if (block_name === "forloop") {
              _this.transform_action_area($target, $related_target, true);
            } else {
              _this.action = window["block_" + block_name];
            }
          }
          $target.attr("filled", "true");
          $target.addClass('caught--it');
          if ($related_target.hasClass('drag-wrap')) {
            $clone = $related_target.detach();
            $clone.removeClass('drag-wrap');
            $clone.removeClass('getting--dragged');
            $clone.appendTo('.drop-zone');
            x = $target.position().left + 5;
            y = $target.position().top;
            $clone.css({
              '-webkit-transform': "translate(" + x + "px, " + y + "px)",
              'position': 'absolute'
            });
            $clone.attr('data-x', x);
            $clone.attr('data-y', y);
            items = $(".drag-wrap");
            return onScroll();
          }
        };
      })(this),
      ondropdeactivate: function(event) {
        $target = $(event.target);
        return $target.removeClass('can--drop', 'can--catch');
      }
    });
  }

  control_for_loop_.prototype.transform_action_area = function($target, $block, isLoop) {
    var control_condition;
    $block.remove();
    $target.html(" ");
    $target.removeClass();
    $target.css({
      "width": "auto",
      "height": "auto"
    });
    $target.attr({
      "role": "whatever"
    });
    control_condition = null;
    if (isLoop) {
      control_condition = new control_for_loop_($target);
      new draggable_control_for_loop_();
    } else {
      control_condition = new control_if_then_($target);
      new draggable_control_if_then_();
    }
    return this.action = control_condition;
  };

  control_for_loop_.prototype.run = function(outer_cb) {
    return async.forEachOfSeries(this.array.run(), (function(_this) {
      return function(element, i, cb) {
        _this.action.run(cb, element);
      };
    })(this), function(err) {
      if (outer_cb != null) {
        return outer_cb();
      }
    });
  };

  return control_for_loop_;

})();
