// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.draggable_control_for_loop_ = (function() {
  function draggable_control_for_loop_() {
    this.run = bind(this.run, this);
    var css;
    css = "		";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable\" name=\"forloop\">\n	FOR LOOP\n</div>").appendTo(".drag-zone");
  }

  draggable_control_for_loop_.prototype.run = function() {};

  return draggable_control_for_loop_;

})();
