// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.draggable_control_if_then_ = (function() {
  function draggable_control_if_then_() {
    this.run = bind(this.run, this);
    var css;
    css = "		";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable\" name=\"ifthen\">\n	IF THEN BLOCK\n	<!--<div id='if' class=\"text\" >IF</div>\n	<div id='block1' class=\"dropzone\">BLOCK1</div>\n	<div id='operator' class=\"dropzone\">________</div>\n	<div id='block2' class='dropzone'>BLOCK2</div>\n	<div id='then' class='text'>THEN</div>\n	<div id='block3' class='dropzone'>DO THIS</div>-->\n</div>").appendTo(".drag-zone");
  }

  draggable_control_if_then_.prototype.run = function() {};

  return draggable_control_if_then_;

})();
